name: adlg

channels:
  - defaults
  - pytorch
  - conda-forge
  
dependencies:
  - python=3.9
  - pytorch::pytorch>=2.0.0
  - pytorch-lightning>=2.0
  - numpy
  - pandas
  - scikit-learn>=1.2.0
  - jupyter
  - jupyterlab
  - seaborn
  - matplotlib
  - pip>=21.0.1
  - tqdm
  - tensorboard>=2.11.0
  - wandb>=0.14.0
  - networkx
  - gensim
  - plotly
  # - pip:
  #   - pyg_lib
  #   - torch_scatter
  #   - torch_sparse
  #   - torch_cluster
  #   - torch_spline_conv -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html